version: "3.3"

services:
  db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5432" ]
      interval: 30s
      timeout: 10s
      retries: 5
    container_name: db

  pgadmin:
    image: dpage/pgadmin4:6.18
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    container_name: pgadmin

  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./app:/src/app
      - ./alembic:/src/alembic
    restart: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: uvicorn.access
    container_name: app

  prometheus:
    image: prom/prometheus:v2.40.7
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    container_name: prometheus

  grafana:
    build: ./grafana
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    user: "1000"
    container_name: grafana

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    depends_on:
      - elasticsearch
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    container_name: fluentd

  elasticsearch:
    image: elasticsearch:8.5.3
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"
    container_name: es

  kibana:
    image: kibana:8.5.3
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    container_name: kibana


volumes:
  db-data:
