version: "3.3"

services:
  db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5432" ]
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"

  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./app:/src/app
      - ./alembic:/src/alembic
    restart: on-failure

  prometheus:
    image: prom/prometheus:main
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:main
    volumes:
      - ./prometheus/datasource.yml:/etc/grafana/provisioning/datasource.yml
    ports:
      - "3000:3000"


volumes:
  db-data:
